Repository sonata-project/SonataDoctrineMongoDBAdminBundle, pull requests merged in 2020-11, with the labels that each got.

#459 Remove deprecations constructing FieldDescription
  composer.json
  src/Admin/FieldDescription.php
  src/Model/ModelManager.php
  tests/Admin/FieldDescriptionTest.php
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/FormContractorTest.php
  tests/Builder/ListBuilderTest.php
  tests/Builder/ShowBuilderTest.php
  tests/Model/ModelManagerTest.php
Labels: patch

#462 Add Next major comment related to https://github.com/sonata-project/SonataAdminBundle/pull/6578
  src/Builder/DatagridBuilder.php
Labels: pedantic

#468 Return null instead of false respecting the interface
  UPGRADE-3.x.md
  src/Guesser/FilterTypeGuesser.php
  tests/Guesser/FilterTypeGuesserTest.php
Labels: patch

#470 Fix returning nested array with identifiers
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: patch

#473 Deprecate ModelManager methods already deprecated in the interface
  UPGRADE-3.x.md
  composer.json
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: minor

#479 Fix not to call AdminInterface::id without object
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#481 Fix NEXT_MAJOR comments
  src/Model/ModelManager.php
  tests/Filter/FilterTest.php
Labels: pedantic
