Repository sonata-project/SonataDoctrineMongoDBAdminBundle, pull requests merged in 2021-01, with the labels that each got.

#497 Fix deprecations introduced in admin-bundle
  composer.json
  src/Builder/DatagridBuilder.php
  src/Filter/Filter.php
  tests/Admin/FieldDescriptionTest.php
  tests/Filter/FilterTest.php
Labels: patch

#504 Remove suggested package
  composer.json
Labels: pedantic

#503 [Tests] Split fixtures into files
  tests/App/DataFixtures/MongoDB/AuthorFixtures.php
  tests/App/DataFixtures/MongoDB/BookFixtures.php
  tests/App/DataFixtures/MongoDB/CategoryFixtures.php
  tests/App/config/services.php
Labels: pedantic

#515 Close API
  src/Admin/FieldDescription.php
  src/Builder/DatagridBuilder.php
  src/Builder/FormContractor.php
  src/Builder/ListBuilder.php
  src/Builder/ShowBuilder.php
  src/Datagrid/Pager.php
  src/Datagrid/ProxyQuery.php
  src/DependencyInjection/Compiler/AddGuesserCompilerPass.php
  src/DependencyInjection/Compiler/AddTemplatesCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataDoctrineMongoDBAdminExtension.php
  src/Filter/BooleanFilter.php
  src/Filter/CallbackFilter.php
  src/Filter/ChoiceFilter.php
  src/Filter/DateFilter.php
  src/Filter/DateTimeFilter.php
  src/Filter/ModelFilter.php
  src/Filter/NumberFilter.php
  src/Filter/StringFilter.php
  src/Guesser/FilterTypeGuesser.php
  src/Guesser/TypeGuesser.php
  src/Model/ModelManager.php
  src/SonataDoctrineMongoDBAdminBundle.php
  src/Util/ObjectAclManipulator.php
  tests/Admin/FieldDescriptionTest.php
  tests/Builder/FormContractorTest.php
  tests/Builder/ListBuilderTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Filter/BooleanFilterTest.php
  tests/Filter/CallbackFilterTest.php
  tests/Filter/ChoiceFilterTest.php
  tests/Filter/FilterTest.php
  tests/Filter/ModelFilterTest.php
  tests/Filter/NumberFilterTest.php
  tests/Filter/StringFilterTest.php
  tests/Guesser/FilterTypeGuesserTest.php
  tests/SonataDoctrineMongoDBAdminBundleTest.php
  tests/Util/ObjectAclManipulatorTest.php
Labels: major

#519 cleanup NEXT_MAJOR comments
  src/Admin/FieldDescription.php
  src/Builder/DatagridBuilder.php
  src/Datagrid/ProxyQuery.php
  src/Filter/AbstractDateFilter.php
  src/Filter/Filter.php
  src/Model/ModelManager.php
  src/Util/ObjectAclManipulator.php
  tests/Admin/FieldDescriptionTest.php
  tests/Builder/DatagridBuilderTest.php
  tests/Builder/ListBuilderTest.php
  tests/Builder/ShowBuilderTest.php
  tests/Datagrid/ProxyQueryTest.php
  tests/Filter/FilterTest.php
  tests/Model/ModelManagerTest.php
Labels: major

#524 Use FieldDescriptionInterface::TYPE_* constants
  src/Guesser/TypeGuesser.php
  tests/Builder/ListBuilderTest.php
  tests/Builder/ShowBuilderTest.php
Labels: pedantic
