Repository sonata-project/SonataDoctrineMongoDBAdminBundle, pull requests merged in 2021-09, with the labels that each got.

#659 Remove default route
  composer.json
  src/FieldDescription/FieldDescriptionFactory.php
  tests/FieldDescription/FieldDescriptionFactoryTest.php
Labels: major

#666 Update docs for filters
  docs/reference/filter_field_definition.rst
Labels: docs

#680 Fix not setting field_name when filtering
  src/Builder/DatagridBuilder.php
  tests/Builder/DatagridBuilderTest.php
Labels: patch

#684 Update homepage
  composer.json
Labels: pedantic
