Repository sonata-project/SonataDoctrineMongoDBAdminBundle, pull requests merged in 2021-05, with the labels that each got.

#584 fix form and filter template registration
  composer.json
  src/DependencyInjection/Compiler/AddGuesserCompilerPass.php
  src/DependencyInjection/Compiler/AddTemplatesCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/SonataDoctrineMongoDBAdminBundle.php
  tests/DependencyInjection/Compiler/AddTemplatesCompilerPassTest.php
Labels: bug

#594 Move options to filter definition
  src/FieldDescription/FilterTypeGuesser.php
  src/Filter/BooleanFilter.php
  src/Filter/NumberFilter.php
  src/Filter/StringFilter.php
  tests/FieldDescription/FilterTypeGuesserTest.php
  tests/Filter/BooleanFilterTest.php
  tests/Filter/ModelFilterTest.php
  tests/Filter/NumberFilterTest.php
  tests/Filter/StringFilterTest.php
Labels: pedantic

#586 Filter data forward compatibility
  UPGRADE-3.x.md
  src/Filter/CallbackFilter.php
  tests/Filter/CallbackFilterTest.php
  tests/Util/CallbackClass.php
Labels: minor

#599 Deprecate ProxyQuery::getSingleScalarResult method
  UPGRADE-3.x.md
  src/Datagrid/ProxyQuery.php
Labels: minor
