Repository sonata-project/SonataDoctrineMongoDBAdminBundle, pull requests merged in 2023-04, with the labels that each got.

#811 Catch MongoDBExceptions to throw ModelManagerExceptions
  src/Model/ModelManager.php
Labels: patch

#813 Improve exception message at `ModelManager::batchDelete()`
  src/Model/ModelManager.php
  tests/Model/ModelManagerTest.php
Labels: minor

#816 Drop support for Symfony 4 and Twig 2
  .github/workflows/test.yaml
  composer.json
  src/Resources/config/doctrine_mongodb.php
  src/Resources/config/doctrine_mongodb_filter_types.php
  src/Resources/config/security.php
  tests/App/AppKernel.php
  tests/App/config/config.yaml
  tests/App/config/config_symfony_v5.yaml
  tests/App/config/config_v5.yml
  tests/App/config/security_v4.yml
  tests/App/config/security_v5.yml
  tests/App/config/services.php
Labels: minor

#819 DevKit updates for 4.x branch
  README.md
Labels: automerge
