Repository sonata-project/SonataDoctrineMongoDBAdminBundle, pull requests merged in 2023-05, with the labels that each got.

#821 DevKit updates for 4.x branch
  .github/workflows/documentation.yaml
  .readthedocs.yaml
  docs/conf.py
  docs/requirements.txt
Labels: automerge, dev-kit

#824 Up rector to 0.16
  composer.json
Labels: pedantic

#822 DevKit updates for 4.x branch
  .github/FUNDING.yml
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#825 Add support for form-extensions 2.0
  composer.json
Labels: minor

#826 Release 4.10.0
  CHANGELOG.md
Labels: dev-kit
